### ISSUE TITLE
Where to install mods (macos)

### ISSUE THREAD

**Issue by SirHazza** [balamod/balamod#49]
I've successfully installed Balamod, and I can use it in game, and install mods from the repo list.

However no documentation is given under **How to Install Mods**, of which directory to place external mods in on macos?

I couldn't find anything in obivous in the games directory, `~/Library/Application Support/Steam/steamapps/common/Balatro/Balatro.app/Contents`

**Comment by UwUDev** [comment]
You should check in the new doc https://balamod.github.io/mod-loading.html

We will add it in the readme on next update
