### ISSUE TITLE
Balamod not removing mods properly

### ISSUE THREAD

**Issue by TheVekter** [balamod/balamod#53]
I installed Slutty Joker from the in-game menu, then disabled it because it seems to not be working. I'm still getting it in my runs.

**Comment by UwUDev** [comment]
Some mods use injection but don't necessarily provide for "de-injection", this problem is rather linked to the mod itself and not to balamod

**Comment by TheVekter** [comment]
> Some mods use injection but don't necessarily provide for "de-injection", this problem is rather linked to the mod itself and not to balamod

With all due respect, isn't removing the mod something the loader normally does and not something that the mod itself handles? Is there a way to manually remove a mod if the mod author hasn't baked that into the mod itself?

**Comment by UwUDev** [comment]
If you're talking about uninstalling a mod it's now handled in balalib https://github.com/balamod/balalib/blob/125e7b572d47c7e1d7da39ca137938e37fda1586/src/mods.rs#L213

You can manually remove a mod in `%appdata%/balatro/mods/`
